org: mannypotter
app: sls-ts-app
service:
  name: sls-ts
# app and org for use with dashboard.serverless.com

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  doofus:
    handler: handler.doofus
    events:
      - http:
          method: get
          path: doofus